name: build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build images
        run: |
          ./build.sh bookworm 1.10.1
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: "*.deb"
